baseURL = "https://123dev.email"
languageCode = "en-us"
title = "123 dev"

disableKinds = "RSS"
theme = "hermit"

[author]
  name = "Justin Garrison"
  url = "https://twitter.com/rothgar"

[taxonomies]
  tag = "tags"

[params]
  dateformShort   = "Jan 2"

  homeSubtitle = "A newsletter to make you a better developer with the power of gifs."
  description = "A newsletter to make you a better developer with the power of gifs."
  images = ["og-banner.png"]

[menu]

  [[menu.main]]
    name = "Archive"
    url = "https://buttondown.email/123dev/archive"
    weight = 20
