baseURL = "https://123dev.email/"
languageCode = "en-us"
title = "123 dev"
theme = "hello-friend-ng"
paginate = 5

[author]
  name = "Justin Garrison"
  url = "https://twitter.com/rothgar"

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "A newsletter to make you a better developer with the power of gifs."
  description = "A newsletter to make you a better developer with the power of gifs."

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/123devEmail"

[languages]
  [languages.en]
    title = "123 dev newsletter"
    subtitle = "A newsletter to make you a better developer with the power of gifs."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$HOME"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
    name = "Archive"
    url = "/posts"
    identifier = "archive"
