name: automatic deploy
on:
  schedule:
    - cron:  '13 20 * * 2'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl --request POST "${VERCEL_URL}"
